#pragma once
#include "../core.hh"

namespace mm{
extern const element_meta mm_cap;
extern const element_meta mm_cause;
extern const element_meta nw_feature_support ;
extern const element_meta nw_slicing_ind;
extern const element_meta eps_nas_msg_container;
extern const element_meta ue_status;
extern const element_meta last_visited_tai;
extern const element_meta nc_native_nas_ksi;
extern const element_meta payload_container;
extern const element_meta ladn_indication;
extern const element_meta ue_security_capability;
extern const element_meta s1_ue_net_capability;
extern const element_meta ue_usage_setting;
extern const element_meta allowed_pdu_ses_status;
extern const element_meta aguti_mobile_id;
extern const element_meta payload_container_type;
extern const element_meta update_type;
extern const element_meta requested_drx_param;
extern const element_meta mico_indication;
extern const element_meta requested_nssai;
extern const element_meta guti_mobile_id;
extern const element_meta ladn_information;
extern const element_meta service_area_list;
extern const element_meta t3512_gprs_timer_3;
extern const element_meta de_reg_timer_gprs_timer2;
extern const element_meta t3502_gprs_timer_2;
extern const element_meta emergency_num_list;
extern const element_meta ext_emerge_num_list;
extern const element_meta sor_trans_cont;
extern const element_meta eap_message;
extern const element_meta nssai_inclusion_mode;
extern const element_meta operator_defined_acd;
extern const element_meta nego_drx_param;
extern const element_meta n3gpp_nw_provided_policies;
extern const element_meta registration_result;
extern const element_meta authentication_failure_parameter;
extern const element_meta auth_param_rand;
extern const element_meta auth_param_autn;
extern const element_meta auth_resp_param;
extern const element_meta configure_update_indication;
extern const element_meta day_saving_time;
extern const element_meta full_name_network;
extern const element_meta short_name_network;
extern const element_meta local_timezone;
extern const element_meta timezone_time;
extern const element_meta operator_defined_access_category_defs;
extern const element_meta sms_ind;
extern const element_meta configured_nssai ;
extern const element_meta mobile_id;
extern const element_meta t3346_gprs_timer2;
extern const element_meta pdu_session_id;
extern const element_meta backoff_gprs_timer3;
extern const element_meta plmn_list;
extern const element_meta sec_algo;
extern const element_meta replayed_ue_sec_cap;
extern const element_meta imeisv_req;
extern const element_meta selected_eps_security_algo;
extern const element_meta additional_sec_info;
extern const element_meta replayed_s1_ue_sec_cap;
extern const element_meta pdu_ses_react_res;
extern const element_meta pdu_session_reactive_result_error_cause;
extern const element_meta s_tmsi;
extern const element_meta uplink_data_status;
extern const element_meta old_pdu_ses_id;
extern const element_meta request_type;
extern const element_meta nas_ksi;
extern const element_meta nas_msg_container;
extern const element_meta abba;
extern const element_meta eps_bearer_ctx_status;
extern const element_meta allowed_nssai;
extern const element_meta tracking_area_id_list;
extern const element_meta rejected_nssai;
extern const element_meta pdu_ses_status;
extern const element_meta imeisv_mobile_id;

} // namespace
