#pragma once

# define NASNR_COMPILER_IS_Clang 0
# define NASNR_COMPILER_IS_GNU 0
# define NASNR_COMPILER_IS_MSVC 0


#if defined(__clang__)
# undef NASNR_COMPILER_IS_Clang
# define NASNR_COMPILER_IS_Clang 1

#elif defined(__GNUC__) || defined(__GNUG__)
# undef NASNR_COMPILER_IS_GNU
# define NASNR_COMPILER_IS_GNU 1

#elif defined(_MSC_VER)
# undef NASNR_COMPILER_IS_MSVC
# define NASNR_COMPILER_IS_MSVC 1


#endif

#  if NASNR_COMPILER_IS_GNU
#      define NASNR_COMPILER_CXX_VARIADIC_TEMPLATES 1
#      define NASNR_COMPILER_CXX_CONSTEXPR 1

#      define NASNR_COMPILER_CXX_FINAL 1

#      define NASNR_COMPILER_CXX_NOEXCEPT 1

#      define NASNR_COMPILER_CXX_OVERRIDE 1

#      define NASNR_COMPILER_CXX_EXTERN_TEMPLATES 1

#      define NASNR_COMPILER_CXX_DELETED_FUNCTIONS 1

#      define NASNR_COMPILER_CXX_ALIGNAS 1

#      define NASNR_COMPILER_CXX_NULLPTR 1

#      define NASNR_COMPILER_CXX_ALIGNOF 1

#      define NASNR_COMPILER_CXX_STATIC_ASSERT 1
#      define NASNR_COMPILER_CXX_ATTRIBUTE_DEPRECATED 1

#define NASNR_COMPILER_CXX_ATTRIBUTE_NODISCARD 1
#define NASNR_COMPILER_CXX_ATTRIBUTE_INLINE 1
#define NASNR_COMPILER_CXX_BRACE_OR_EQUAL_INITIALIZER 1
#define NASNR_COMPILER_CXX_TYPE_DEDUCE 1
#define NASNR_COMPILER_CXX_17_FEATURE 1

#  elif NASNR_COMPILER_IS_MSVC

#    if _MSC_VER >= 1800
#      define NASNR_COMPILER_CXX_VARIADIC_TEMPLATES 1
#    else
#      define NASNR_COMPILER_CXX_VARIADIC_TEMPLATES 0
#    endif

#    if _MSC_VER >= 1900
#      define NASNR_COMPILER_CXX_CONSTEXPR 1
#    else
#      define NASNR_COMPILER_CXX_CONSTEXPR 0
#    endif

#    if _MSC_VER >= 1700
#      define NASNR_COMPILER_CXX_FINAL 1
#    else
#      define NASNR_COMPILER_CXX_FINAL 0
#    endif

#    if _MSC_VER >= 1900
#      define NASNR_COMPILER_CXX_NOEXCEPT 1
#    else
#      define NASNR_COMPILER_CXX_NOEXCEPT 0
#    endif

#    if _MSC_VER >= 1600
#      define NASNR_COMPILER_CXX_OVERRIDE 1
#    else
#      define NASNR_COMPILER_CXX_OVERRIDE 0
#    endif

#    if _MSC_VER >= 1600
#      define NASNR_COMPILER_CXX_EXTERN_TEMPLATES 1
#    else
#      define NASNR_COMPILER_CXX_EXTERN_TEMPLATES 0
#    endif

#    if _MSC_VER >= 1900
#      define NASNR_COMPILER_CXX_DELETED_FUNCTIONS 1
#    else
#      define NASNR_COMPILER_CXX_DELETED_FUNCTIONS 0
#    endif

#if _MSC_VER >= 1900
#define NASNR_COMPILER_CXX_DEFAULT_FUNCTIONS 1
#else
#define NASNR_COMPILER_CXX_DEFAULT_FUNCTIONS 0
#endif

#    if _MSC_VER >= 1900
#      define NASNR_COMPILER_CXX_ALIGNAS 1
#    else
#      define NASNR_COMPILER_CXX_ALIGNAS 0
#    endif

#    if _MSC_VER >= 1600
#      define NASNR_COMPILER_CXX_NULLPTR 1
#    else
#      define NASNR_COMPILER_CXX_NULLPTR 0
#    endif

#    if _MSC_VER >= 1900
#      define NASNR_COMPILER_CXX_ALIGNOF 1
#    else
#      define NASNR_COMPILER_CXX_ALIGNOF 0
#    endif

#    if _MSC_VER >= 1600
#      define NASNR_COMPILER_CXX_STATIC_ASSERT 1
#    else
#      define NASNR_COMPILER_CXX_STATIC_ASSERT 0
#    endif

#    if _MSC_VER >= 1900
#      define NASNR_COMPILER_CXX_ATTRIBUTE_DEPRECATED 1
#    else
#      define NASNR_COMPILER_CXX_ATTRIBUTE_DEPRECATED 0
#    endif

#if _MSC_VER >= 1900
#define NASNR_COMPILER_CXX_ATTRIBUTE_NODISCARD 1
#else
#define NASNR_COMPILER_CXX_ATTRIBUTE_NODISCARD 0
#endif

#if _MSC_VER >= 1900
#define NASNR_COMPILER_CXX_INLINE 1
#else
#define NASNR_COMPILER_CXX_INLINE 0
#endif

#if _MSC_VER >= 1900
#define NASNR_COMPILER_CXX_BRACE_OR_EQUAL_INITIALIZER 1
#else
#define NASNR_COMPILER_CXX_BRACE_OR_EQUAL_INITIALIZER 0
#endif

#if _MSC_VER >= 1900
#define NASNR_COMPILER_CXX_TYPE_DEDUCE 1
#define NASNR_COMPILER_CXX_17_FEATURE 1
#else
#define NASNR_COMPILER_CXX_TYPE_DEDUCE 0
#define NASNR_COMPILER_CXX_17_FEATURE 0
#endif

#  elif NASNR_COMPILER_IS_Clang
#      define NASNR_COMPILER_CXX_VARIADIC_TEMPLATES 1
#      define NASNR_COMPILER_CXX_CONSTEXPR 1
#      define NASNR_COMPILER_CXX_FINAL 1
#      define NASNR_COMPILER_CXX_NOEXCEPT 1
#      define NASNR_COMPILER_CXX_OVERRIDE 1
#      define NASNR_COMPILER_CXX_EXTERN_TEMPLATES 1
#      define NASNR_COMPILER_CXX_DELETED_FUNCTIONS 1
#      define NASNR_COMPILER_CXX_ALIGNAS 1
#      define NASNR_COMPILER_CXX_NULLPTR 1
#      define NASNR_COMPILER_CXX_ALIGNOF 1
#      define NASNR_COMPILER_CXX_STATIC_ASSERT 1
#      define NASNR_COMPILER_CXX_ATTRIBUTE_DEPRECATED 1
#define NASNR_COMPILER_CXX_ATTRIBUTE_NODISCARD 1
#define NASNR_COMPILER_CXX_ATTRIBUTE_INLINE 1
#define NASNR_COMPILER_CXX_BRACE_OR_EQUAL_INITIALIZER 1

#define NASNR_COMPILER_CXX_TYPE_DEDUCE 1
#define NASNR_COMPILER_CXX_17_FEATURE 1

#  else
#    error Unsupported compiler
#  endif

#  if defined(NASNR_COMPILER_CXX_CONSTEXPR) && NASNR_COMPILER_CXX_CONSTEXPR
#    define NASNR_CONSTEXPR constexpr
#  else
#    define NASNR_CONSTEXPR
#  endif


#  if defined(NASNR_COMPILER_CXX_FINAL) && NASNR_COMPILER_CXX_FINAL
#    define NASNR_FINAL final
#  else
#    define NASNR_FINAL
#  endif


#  if defined(NASNR_COMPILER_CXX_NOEXCEPT) && NASNR_COMPILER_CXX_NOEXCEPT
#    define NASNR_NOEXCEPT noexcept
#    define NASNR_NOEXCEPT_EXPR(X) noexcept(X)
#  else
#    define NASNR_NOEXCEPT
#    define NASNR_NOEXCEPT_EXPR(X)
#  endif


#  if defined(NASNR_COMPILER_CXX_OVERRIDE) && NASNR_COMPILER_CXX_OVERRIDE
#    define NASNR_OVERRIDE override
#  else
#    define NASNR_OVERRIDE
#  endif


#  if defined(NASNR_COMPILER_CXX_EXTERN_TEMPLATES) && NASNR_COMPILER_CXX_EXTERN_TEMPLATES
#    define NASNR_EXTERN_TEMPLATE extern
#  else
#    define NASNR_EXTERN_TEMPLATE
#  endif


#  if defined(NASNR_COMPILER_CXX_DELETED_FUNCTIONS) && NASNR_COMPILER_CXX_DELETED_FUNCTIONS
#    define NASNR_DELETED_FUNCTION = delete
#  else
#    define NASNR_DELETED_FUNCTION
#  endif

#if defined(NASNR_COMPILER_CXX_DEFAULT_FUNCTIONS) && NASNR_COMPILER_CXX_DEFAULT_FUNCTIONS
#define NASNR_DEFAULT_FUNCTION = default
#else
#define NASNR_DEFAULT_FUNCTION
#endif

#if defined(NASNR_COMPILER_CXX_ATTRIBUTE_NODISCARD) && NASNR_COMPILER_CXX_ATTRIBUTE_NODISCARD
#define NASNR_NODISCARD [[nodiscard]]
#else
#define NASNR_NODISCARD
#endif

#if defined(NASNR_COMPILER_CXX_TYPE_DEDUCE) && \
    NASNR_COMPILER_CXX_TYPE_DEDUCE
#define NASNR_AUTO(X) auto
#else
#define NASNR_AUTO(X) X
#endif

#if defined(NASNR_COMPILER_CXX_INLINE) && NASNR_COMPILER_CXX_INLINE
#define NASNR_INLINE inline
#else
#define NASNR_INLINE __declspec(selectany) extern
#endif

#if defined(NASNR_COMPILER_CXX_BRACE_OR_EQUAL_INITIALIZER) && NASNR_COMPILER_CXX_BRACE_OR_EQUAL_INITIALIZER
#define NASNR_EQUAL_INIT(X) = X
#define NASNR_LIST_INIT(X, ...) {__VA_ARGS__}
#else
#define NASNR_EQUAL_INIT(X)
#define NASNR_LIST_INIT(X, ...) X(__VA_ARGS__)
#endif

#  if defined(NASNR_COMPILER_CXX_ALIGNAS) && NASNR_COMPILER_CXX_ALIGNAS
#    define NASNR_ALIGNAS(X) alignas(X)
#  elif NASNR_COMPILER_IS_GNU || NASNR_COMPILER_IS_Clang || NASNR_COMPILER_IS_AppleClang
#    define NASNR_ALIGNAS(X) __attribute__ ((__aligned__(X)))
#  elif NASNR_COMPILER_IS_MSVC
#    define NASNR_ALIGNAS(X) __declspec(align(X))
#  else
#    define NASNR_ALIGNAS(X)
#  endif


#  if defined(NASNR_COMPILER_CXX_NULLPTR) && NASNR_COMPILER_CXX_NULLPTR
#    define NASNR_NULLPTR nullptr
#  elif NASNR_COMPILER_IS_GNU
#    define NASNR_NULLPTR __null
#  else
#    define NASNR_NULLPTR 0
#  endif


#  if defined(NASNR_COMPILER_CXX_ALIGNOF) && NASNR_COMPILER_CXX_ALIGNOF
#    define NASNR_ALIGNOF(X) alignof(X)
#  elif NASNR_COMPILER_IS_GNU || NASNR_COMPILER_IS_Clang || NASNR_COMPILER_IS_AppleClang
#    define NASNR_ALIGNOF(X) __alignof__(X)
#  elif NASNR_COMPILER_IS_MSVC
#    define NASNR_ALIGNOF(X) __alignof(X)
#  endif

#  if defined(NASNR_COMPILER_CXX_STATIC_ASSERT) && NASNR_COMPILER_CXX_STATIC_ASSERT
#    define NASNR_STATIC_ASSERT(X) static_assert(X, #X)
#    define NASNR_STATIC_ASSERT_MSG(X, MSG) static_assert(X, MSG)
#  else
#    define NASNR_STATIC_ASSERT_JOIN(X, Y) NASNR_STATIC_ASSERT_JOIN_IMPL(X, Y)
#    define NASNR_STATIC_ASSERT_JOIN_IMPL(X, Y) X##Y
template<bool> struct NASNRStaticAssert;
template<> struct NASNRStaticAssert<true>{};
#    define NASNR_STATIC_ASSERT(X) enum { NASNR_STATIC_ASSERT_JOIN(NASNRStaticAssertEnum, __LINE__) = sizeof(NASNRStaticAssert<X>) }
#    define NASNR_STATIC_ASSERT_MSG(X, MSG) enum { NASNR_STATIC_ASSERT_JOIN(NASNRStaticAssertEnum, __LINE__) = sizeof(NASNRStaticAssert<X>) }
#  endif


#  ifndef NASNR_DEPRECATED
#    if defined(NASNR_COMPILER_CXX_ATTRIBUTE_DEPRECATED) && NASNR_COMPILER_CXX_ATTRIBUTE_DEPRECATED
#      define NASNR_DEPRECATED [[deprecated]]
#      define NASNR_DEPRECATED_MSG(MSG) [[deprecated(MSG)]]
#    elif NASNR_COMPILER_IS_GNU || NASNR_COMPILER_IS_Clang
#      define NASNR_DEPRECATED __attribute__((__deprecated__))
#      define NASNR_DEPRECATED_MSG(MSG) __attribute__((__deprecated__(MSG)))
#    elif NASNR_COMPILER_IS_MSVC
#      define NASNR_DEPRECATED __declspec(deprecated)
#      define NASNR_DEPRECATED_MSG(MSG) __declspec(deprecated(MSG))
#    else
#      define NASNR_DEPRECATED
#      define NASNR_DEPRECATED_MSG(MSG)
#    endif
#  endif



